### PR TITLE
Update chinese messages.json

### PR DESCRIPTION
**Pull request by catcat520**

### CODE REVIEW

**Comment by schomery** [comment]
@catcat520 can you please join https://www.transifex.com/github-7/Stylus/dashboard/?

**Comment by catcat520** [comment]
ok let's do it

**Comment by catcat520** [comment]
finish the chinese messages.json in https://www.transifex.com/github-7/Stylus/

**Comment by schomery** [comment]
Perfect! Thanks @catcat520 

It is now merged in the master branch. Please give it a try; https://github.com/schomery/stylish-chrome/archive/master.zip

Also please finish the `WebStore` file as well. We are going to need it for Opera submission.

**Comment by catcat520** [comment]
@schomery 
yes,i tested master.zip and seems everything work fine

**Comment by catcat520** [comment]
WebStore file done.

**Comment by schomery** [comment]
Great! Thanks for the confirmation @catcat520

**Pull request closed without merging**
