### PR TITLE
Switch info/external style link icons from img to svg

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
Switched info to `i` and found a pretty nice external link icon imo. @tophf As for pixelation on the info icons, you mentioned maybe a lighter color would help. For all icons besides external links, I made them lighter with darker hovers. Besides a really high zoom, I never saw any issue to begin with, but let me know if they're alright. I also changed them to use their exact original dimensions, so maybe that helps.

### CODE REVIEW

**Comment by tophf** [comment]
LGTM!

**Comment by tophf** [comment]
We have an old problem: `(Disabled)` after the icon has an underline. Would be nice of you to fix it :-)

**Comment by narcolepticinsomniac** [comment]
You and I pretty much qualify as a majority vote. It's not like these are some drastic changes. Is there any reason this shouldn't be merged? Wouldn't that make it easier to address whatever compatibility issues there might be with your branch? Besides the svg issue you mentioned, there's also a help icon in the regex help popup. The CSS for it is in `edit.js`, IIRC.

**Comment by tophf** [comment]
Yeah, I think you can merge it. And then I'll rebase my PR.

**Pull request merged**
