### PR TITLE
Fix: don't use null as id

### PR DESCRIPTION
**Pull request by eight04**
Using `null` as the id will throw when inserting to indexedDB.

### CODE REVIEW

**Comment by Mottie** [comment]
Have you encountered this issue? This modification was made [over 2 years ago](https://github.com/openstyles/stylus/commit/449f86e5ef7cfb4da1e2d10105fa95a34ffa86c1#diff-0).

**Comment by eight04** [comment]
> Have you encountered this issue? This modification was made [over 2 years ago](https://github.com/openstyles/stylus/commit/449f86e5ef7cfb4da1e2d10105fa95a34ffa86c1#diff-0).

Yes. I found this when testing #602. After #547, we added `styleManager.importMany` API that doesn't strip `id` property when the `id` is null like `styleManager.importStyle`:
https://github.com/openstyles/stylus/blob/779a6e4e35b63b4c6cccf1a6e1de165ea6c05154/background/style-manager.js#L267-L269

**Comment by narcolepticinsomniac** [comment]
>over 2 years ago 

quick maths

**Comment by Mottie** [comment]
LOL ok 1.5 years... I was rounding up!

**Pull request merged**
