### PR TITLE
Fix linting and make the code more readable

### PR DESCRIPTION
**Pull request by DecentM**
In theory, and as far as I tested, nothing is broken, and no console errors are thrown.

### CODE REVIEW

**Comment by tophf** [comment]
Reformatting won't make the code more readable, refactoring will. Also, are you seriously suggesting a PR that removes and readds files?

**Comment by DecentM** [comment]
Sure it can make it more readable. In the original, there's this line:
```
chrome.runtime.sendMessage({method: "getStyles", matchUrl: location.href, enabled: true, id: request.style.id, asHash: true},
```  
Breaking this up into  
```
chrome.runtime.sendMessage({
    method: "getStyles",
    matchUrl: location.href,
    enabled: true,
    id: request.style.id,
    asHash: true
}, applyStyles);
```  
makes it much better, doesn't it?  

And yes, I accidentally committed a delete on the csslint directory, but force pushing a correct one would break this PR, so re-adding the file is the simplest solution.

**Comment by tophf** [comment]
1. Generally yes, but the overall code structure in Stylish are so bad that such minor reformatting won't help. It simply isn't worth it unless you can guarantee with 100% certainty that your changes didn't break a single thing.
2. Learn git: do a rebase, then use a forced push to rewrite your PR.

**Comment by DecentM** [comment]
1. That's true, but we have to get started somewhere if we want to get anything resembling a full version done. There's such a low amount of feratures that I'm sure moving whitespaces and tabs around didn't break anything.
2. Also true, but I'm not going to stop doing everything until I have 100% learned git.

**Comment by tophf** [comment]
Well, whoever accepts the PR, please use `Squash and merge` button on github then.

**Comment by schomery** [comment]
Guys how about doing this with a node script in two steps? First one for all `*.js` and the second one for all `*.css`

There are pretty stable JavaScript beautifiers out there for node like https://www.npmjs.com/package/js-beautify.

**Comment by silverwind** [comment]
I'd also suggest automating this. You can set up ESLint rules and then run `eslint --fix` to automatically correct a majority of issues.

**Comment by schomery** [comment]
@silverwind can you prepare the ESLint config file?

**Comment by silverwind** [comment]
I can. Do you have any code style preferences or should it just be "what throws the fewest errors"?

**Comment by schomery** [comment]
I am using JSCS with the following config
```
{
  "requireCurlyBraces": [
      "if",
      "else",
      "for",
      "while",
      "do",
      "try",
      "catch"
  ],
  "requireOperatorBeforeLineBreak": true,
  "requireCamelCaseOrUpperCaseIdentifiers": true,
  "maximumLineLength": {
    "value": 120,
    "allowComments": true,
    "allowRegex": true
  },
  "validateIndentation": 2,
  "validateQuoteMarks": "'",

  "disallowMultipleLineStrings": true,
  "disallowMixedSpacesAndTabs": true,
  "disallowTrailingWhitespace": true,
  "disallowSpaceAfterPrefixUnaryOperators": true,

  "requireSpaceAfterKeywords": [
    "if",
    "else",
    "for",
    "while",
    "do",
    "switch",
    "return",
    "try",
    "catch"
  ],
  "requireSpaceBeforeBinaryOperators": [
      "=", "+=", "-=", "*=", "/=", "%=", "<<=", ">>=", ">>>=",
      "&=", "|=", "^=", "+=",

      "+", "-", "*", "/", "%", "<<", ">>", ">>>", "&",
      "|", "^", "&&", "||", "===", "==", ">=",
      "<=", "<", ">", "!=", "!=="
  ],
  "requireSpaceAfterBinaryOperators": true,
  "requireSpacesInConditionalExpression": true,
  "requireSpaceBeforeBlockStatements": true,
  "requireSpacesInForStatement": true,
  "requireLineFeedAtFileEnd": true,
  "requireSpacesInFunctionExpression": {
      "beforeOpeningRoundBrace": true,
      "beforeOpeningCurlyBrace": true
  },
  "disallowSpacesInsideObjectBrackets": "all",
  "disallowSpacesInsideArrayBrackets": "all",
  "disallowSpacesInsideParentheses": true,

  "disallowMultipleLineBreaks": true,
  "disallowNewlineBeforeBlockStatements": true
}
```

**Comment by schomery** [comment]
Mine is based on Google's recommended styling if I recall correctly. Anyhow I am flexible if you want to drop rules to reduce errors.

**Comment by silverwind** [comment]
You ok with converting indentation from tabs to spaces? Spaces are my preference too. :)

**Comment by silverwind** [comment]
Reformatting done here: https://github.com/silverwind/stylish-chrome/commit/3fb03b6c5705c5a3c7666677c625daa2545d444b

I took my personal config and adapted what I could from yours. Still need to test.

**Comment by schomery** [comment]
@silverwind can you please prepare a pull request just for `.editorconfig`, `.eslintignore`, and `.eslintrc` files for now? We can perform the actual cleanup when https://github.com/schomery/stylish-chrome/tree/codemirror-update/ is merged to reduce conflicts.

**Comment by silverwind** [comment]
Can do later today. The fixing was quite a lot of manual work. Initally there were around 8k error, after `eslint --fix` there were around 900 which I had to manually fix. If you can get the CodeMirror branch to comply with the rules, I guess the merge conflicts should be easier to solve.

**Comment by schomery** [comment]
can you simplify the `.eslintrc` file to reduce these errors. If we are dealing with around 900 manual fix, it is very risky to apply these changes to the master branch as we might break things. If this `eslint --fix` doesn't work, we can go with a simpler JS beautifier script.

**Comment by silverwind** [comment]
I'll remove the top rules. The diff will be considerable anyways because of the current mixed spaces/tab and otherwise inconsistent indendation.

**Comment by tophf** [comment]
I've been refactoring a lot of code recently because there are many real, non-cosmetic, issues in the old code. For example, the caching system is being entirely rewritten and improved performance-wise. Ditto for the editor, which will get helluva lot of updates.

We'll revisit the formatting issues after dealing with the pending and upcoming changes. By that time there shouldn't be much left to reformat though because the new code we add/change is basically following the suggestions here as far as I can see.

**Comment by schomery** [comment]
Based on @tophf work on #50, there is no need for the automatic formatting anymore.

**Pull request closed without merging**
